In [1]:
import dhlab as dh

In [23]:
['4'] + ['1','3']

['4', '1', '3']

In [2]:
c = dh.Corpus(doctype="digibok")

In [7]:
counts = dh.Counts(c, words = "han hun".split())

In [8]:
counts.counts

urn,URN:NBN:no-nb_digibok_2008070704011,URN:NBN:no-nb_digibok_2009052604008,URN:NBN:no-nb_digibok_2011070605001,URN:NBN:no-nb_digibok_2012062506017,URN:NBN:no-nb_digibok_2014031006126,URN:NBN:no-nb_digibok_2017080107077,URN:NBN:no-nb_digibok_2018031448055,URN:NBN:no-nb_digibok_2021072948067
word,,,,,,,,
han,121.0,40.0,597.0,3.0,19.0,937.0,5.0,3.0
hun,3.0,0.0,0.0,3.0,21.0,400.0,0.0,0.0

In [14]:
c.corpus[['urn', 'title','year']].values

array([['URN:NBN:no-nb_digibok_2012062506017',
        'OMI og aktuelle skoleforskningsprosjekter : rapport fra konferanse på Sundvolden august 1980',
        1980],
       ['URN:NBN:no-nb_digibok_2011070605001', 'Nær nok : noveller',
        2004],
       ['URN:NBN:no-nb_digibok_2017080107077', 'David Grieve : roman. 1',
        1892],
       ['URN:NBN:no-nb_digibok_2008070704011',
        'Fedreland og fritid : en mellomkrigsstudie i Noregs ungdomslag',
        1995],
       ['URN:NBN:no-nb_digibok_2009052604008',
        'Bedriftslære for yrkesfaga : Arbeidsbok til', 1990],
       ['URN:NBN:no-nb_digibok_2012071908003',
        'Folketellingen 1. november 1960 : tellingsresultater : tilbakegående tall : prognoser : <Kommunevis> : 2027 Nesseby',
        1962],
       ['URN:NBN:no-nb_digibok_2018031448055',
        'Internasjonale lover for turneringsbridge 1987', 1987],
       ['URN:NBN:no-nb_digibok_2014031006126', 'Skorpen', 2011],
       ['URN:NBN:no-nb_digibok_2018021505051',
        'En miljøpolitisk vurdering av det nordiske energimarkedet',
        1990],
       ['URN:NBN:no-nb_digibok_2021072948067',
        'Arabiske kristne og Palestinaspørsmålet', 1979]], dtype=object)

In [16]:
names = {x[0]:' '.join([str(z) for z in x[1:]]) for x in c.corpus[['urn', 'title','year']].values}

In [19]:
counts.counts.rename(columns=names)

urn,Fedreland og fritid : en mellomkrigsstudie i Noregs ungdomslag 1995,Bedriftslære for yrkesfaga : Arbeidsbok til 1990,Nær nok : noveller 2004,OMI og aktuelle skoleforskningsprosjekter : rapport fra konferanse på Sundvolden august 1980 1980,Skorpen 2011,David Grieve : roman. 1 1892,Internasjonale lover for turneringsbridge 1987 1987,Arabiske kristne og Palestinaspørsmålet 1979
word,,,,,,,,
han,121.0,40.0,597.0,3.0,19.0,937.0,5.0,3.0
hun,3.0,0.0,0.0,3.0,21.0,400.0,0.0,0.0

In [20]:
counts.counts

urn,URN:NBN:no-nb_digibok_2008070704011,URN:NBN:no-nb_digibok_2009052604008,URN:NBN:no-nb_digibok_2011070605001,URN:NBN:no-nb_digibok_2012062506017,URN:NBN:no-nb_digibok_2014031006126,URN:NBN:no-nb_digibok_2017080107077,URN:NBN:no-nb_digibok_2018031448055,URN:NBN:no-nb_digibok_2021072948067
word,,,,,,,,
han,121.0,40.0,597.0,3.0,19.0,937.0,5.0,3.0
hun,3.0,0.0,0.0,3.0,21.0,400.0,0.0,0.0